export type BusinessCategory =
  | 'SHOPPING'
  | 'FOOD & RESTAURANTS'
  | 'TRANSPORT'
  | 'DELIVERY & ERRANDS'
  | 'BEAUTY & WELLNESS'
  | 'SERVICES'
  | 'BUY CASH POWER (NAWEC)'
  | 'GOVERNMENT PAYMENTS'
  | 'AI JOBS & INCOME'
  | 'PAYMENTS';

export interface OurWorkItem {
  id: string;
  title: string;
  description: string;
  image: string;
  category?: string;
  completedDate?: string;
  tags?: string[];
}

export interface PartnerReview {
  id: string;
  partnerId: string;
  authorName: string;
  rating: number; // 1 to 5
  date: string;
  comment: string;
  serviceUsed?: string;
  verifiedUser?: boolean;
}

export interface BusinessPartner {
  id: string;
  name: string;
  owner: string;
  description: string;
  category: BusinessCategory | string;
  subcategory: string;
  location: string;
  address: string;
  phone: string;
  whatsapp: string;
  email: string;
  website?: string;
  socialMedia?: string;
  logo: string;
  coverImage: string;
  photos: string[];
  ourWork?: OurWorkItem[];
  reviews?: PartnerReview[];
  openingHours: string;
  deliveryAvailable: boolean;
  deliveryFee: number; // in Dalasi (D)
  estimatedDeliveryTime: string;
  products: ProductItem[];
  services: ServiceItem[];
  promotions?: string;
  rating: number;
  reviewCount: number;
  verificationStatus: 'verified' | 'pending' | 'rejected';
  featuredStatus: boolean;
  activeStatus: boolean;
  active?: boolean;
  verified?: boolean;
  dateAdded: string;
  lastUpdated: string;
}

export type MissingAIRequest = MissingRequestRecord;

export interface AdminStats {
  totalUsers: number;
  activeUsers: number;
  totalBusinesses: number;
  activeBusinesses: number;
  verifiedBusinesses: number;
  totalProducts: number;
  activeAdsCount: number;
  aiSearchesCount: number;
  popularCategories: { category: string; searches: number }[];
  systemHealth: string;
}

export interface ProductItem {
  id: string;
  partnerId: string;
  name: string;
  description: string;
  price: number; // in Dalasi (D)
  currency: string;
  category: string;
  stock: number;
  available: boolean;
  image: string;
  promotion?: string;
  discountPrice?: number;
}

export interface ServiceItem {
  id: string;
  partnerId: string;
  name: string;
  description: string;
  startingPrice: number;
  duration?: string;
  available: boolean;
}

export interface CategoryInfo {
  id: string;
  key: string;
  name: string;
  tagline: string;
  subcategories: string[];
  image: string;
  icon: string;
  color: string;
  displayOrder: number;
  active: boolean;
  featured: boolean;
  aiKeywords: string[];
}

export interface Advertisement {
  id: string;
  title: string;
  advertiser: string;
  description: string;
  ctaText: string;
  ctaLink: string;
  type: 'video' | 'image' | 'campaign';
  mediaUrl: string;
  posterUrl?: string;
  durationSeconds: number;
  active: boolean;
  priority: number;
  targetCategory?: string;
  startDate: string;
  endDate: string;
  impressions: number;
  clicks: number;
  autoGenerated?: boolean;
  badge?: string;
  fileData?: string;
  advertiserLogo?: string;
}

export interface AIInteractionLog {
  id: string;
  timestamp: string;
  userQuery: string;
  aiResponse: string;
  detectedIntent: string;
  matchedPartners: string[];
  missingRequestRecorded?: boolean;
  responseTimeMs: number;
  status: 'success' | 'fallback' | 'missing_item';
}

export interface MissingRequestRecord {
  id: string;
  timestamp: string;
  query: string;
  missingItem: string;
  missingCategory?: string;
  requestedLocation?: string;
  frequency: number;
  resolved: boolean;
  notes?: string;
}

export type AdminRole =
  | 'SUPER_ADMIN'
  | 'ADMIN'
  | 'CONTENT_MANAGER'
  | 'BUSINESS_MANAGER'
  | 'ANALYST'
  | 'SUPPORT';

export type SecurityClearanceTier =
  | 'TIER_1_CORE'
  | 'TIER_2_OPERATIONAL'
  | 'TIER_3_SUPPORT';

export interface AdminUser {
  id: string;
  username: string;
  name: string;
  email: string;
  role: AdminRole;
  phone?: string;
  nationalIdOrNin?: string;
  department?: string;
  securityClearance?: SecurityClearanceTier;
  verifiedPersonal?: boolean;
  verifiedBy?: string;
  verifiedAt?: string;
  twoFactorEnabled?: boolean;
  lastLogin: string;
  active: boolean;
  createdAt?: string;
}

export interface AuditLogEntry {
  id: string;
  timestamp: string;
  adminId: string;
  adminName?: string;
  adminUsername?: string;
  role?: AdminRole;
  action: string;
  targetRecord?: string;
  targetEntity?: string;
  targetId?: string;
  previousValue?: string;
  newValue?: string;
  details?: string;
  result?: 'SUCCESS' | 'FAILURE' | 'WARNING' | string;
}

export interface CashPowerTransaction {
  id: string;
  meterNumber: string;
  meterOwner: string;
  amountDalasi: number;
  phone: string;
  tokenGenerated: string;
  unitsKWh: number;
  tariffGMDPerKWh: number;
  timestamp: string;
  status: 'COMPLETED' | 'PENDING' | 'FAILED';
  isRealGateway: boolean; // clearly distinguish REAL vs DEMO/TEST
}

export interface GovernmentPaymentTransaction {
  id: string;
  serviceType: string;
  tinOrReference: string;
  taxpayerName: string;
  amountDalasi: number;
  phone: string;
  receiptNumber: string;
  status: 'COMPLETED' | 'PENDING';
  isRealGateway: boolean;
  timestamp: string;
}

export interface AIJobListing {
  id: string;
  title: string;
  type: 'Prompt Engineering' | 'Data Annotation' | 'Local Content Writer' | 'AI Tutor' | 'Freelance Microtask';
  compensation: string; // e.g., "D5,000 - D15,000 / month"
  location: string;
  company: string;
  skillsNeeded: string[];
  description: string;
  deadline: string;
}
