export type BusinessCategory =
  | 'SHOPPING'
  | 'FOOD & RESTAURANTS'
  | 'TRANSPORT'
  | 'DELIVERY & ERRANDS'
  | 'BEAUTY & WELLNESS'
  | 'SERVICES'
  | 'HOUSING & PROPERTIES'
  | 'HOTELS & STAYS'
  | 'BUY CASH POWER (NAWEC)'
  | 'GOVERNMENT PAYMENTS'
  | 'AI JOBS & INCOME'
  | 'PAYMENTS';

export interface OurWorkItem {
  id: string;
  title: string;
  description: string;
  image: string;
  category?: string;
  completedDate?: string;
  tags?: string[];
}

export interface PartnerReview {
  id: string;
  partnerId: string;
  authorName: string;
  rating: number; // 1 to 5
  date: string;
  comment: string;
  serviceUsed?: string;
  verifiedUser?: boolean;
}

export interface BusinessPartner {
  id: string;
  name: string;
  owner: string;
  description: string;
  category: BusinessCategory | string;
  subcategory: string;
  location: string;
  address: string;
  phone: string;
  whatsapp: string;
  email: string;
  website?: string;
  socialMedia?: string;
  logo: string;
  coverImage: string;
  photos: string[];
  videoUrl?: string;
  ourWork?: OurWorkItem[];
  reviews?: PartnerReview[];
  openingHours: string;
  deliveryAvailable: boolean;
  deliveryFee: number; // in Dalasi (D)
  estimatedDeliveryTime: string;
  products: ProductItem[];
  services: ServiceItem[];
  promotions?: string;
  rating: number;
  reviewCount: number;
  verificationStatus: 'verified' | 'pending' | 'rejected';
  featuredStatus: boolean;
  activeStatus: boolean;
  active?: boolean;
  verified?: boolean;
  featured?: boolean;
  dateAdded: string;
  lastUpdated: string;
}

export type Product = ProductItem;
export type Service = ServiceItem;

export type MissingAIRequest = MissingRequestRecord;

export interface AdminStats {
  totalUsers: number;
  activeUsers: number;
  totalBusinesses: number;
  activeBusinesses: number;
  verifiedBusinesses: number;
  totalProducts: number;
  activeAdsCount: number;
  aiSearchesCount: number;
  popularCategories: { category: string; searches: number }[];
  systemHealth: string;
}

export interface ProductItem {
  id: string;
  partnerId: string;
  name: string;
  description: string;
  price: number; // in Dalasi (D)
  currency: string;
  category: string;
  stock: number;
  available: boolean;
  inStock?: boolean;
  image: string;
  promotion?: string;
  discountPrice?: number;
}

export interface ServiceItem {
  id: string;
  partnerId: string;
  partnerName?: string;
  name: string;
  description: string;
  startingPrice: number;
  price?: number;
  pricingType?: string; // 'Fixed' | 'Hourly' | 'Per Visit' | 'Per Infusion' | 'Overnight (8-12 hrs)' | 'Hourly / Shift'
  duration?: string;
  durationMinutes?: number;
  available: boolean;
  category?: string;
  subcategory?: string;
  serviceArea?: string;
  appointmentRequirements?: string;
  verificationStatus?: 'verified' | 'pending' | 'unverified';
  credentialsInfo?: string;
  activeStatus?: boolean;
  isActive?: boolean;
  active?: boolean;
}

export const HEALTHCARE_SERVICES_LIST = [
  'Registered Nurse (RN)',
  'Home Nursing',
  'Elderly Care',
  'Post-Surgery Care',
  'Wound Care & Dressing Changes',
  'Medication Administration',
  'IV Therapy',
  'Blood Pressure Monitoring',
  'Diabetes Care',
  'Catheter Care',
  'Palliative Care',
  'Overnight Caregiver',
  'Private Duty Nurse',
  'Baby & Newborn Nurse',
  'Health Check Visits'
] as const;

export type HealthcareServiceName = typeof HEALTHCARE_SERVICES_LIST[number];

export interface CategoryInfo {
  id: string;
  key: string;
  name: string;
  tagline: string;
  subcategories: string[];
  image: string;
  icon: string;
  color: string;
  displayOrder: number;
  active: boolean;
  featured: boolean;
  aiKeywords: string[];
}

export interface Advertisement {
  id: string;
  title: string;
  advertiser: string;
  description: string;
  ctaText: string;
  ctaLink: string;
  type: 'video' | 'image' | 'campaign';
  mediaUrl: string;
  posterUrl?: string;
  durationSeconds: number;
  active: boolean;
  priority: number;
  targetCategory?: string;
  partnerId?: string;
  headline?: string;
  subtext?: string;
  thumbnailUrl?: string;
  startDate: string;
  endDate: string;
  impressions: number;
  clicks: number;
  autoGenerated?: boolean;
  badge?: string;
  fileData?: string;
  advertiserLogo?: string;
}

export interface AIInteractionLog {
  id: string;
  timestamp: string;
  userQuery: string;
  aiResponse: string;
  detectedIntent: string;
  matchedPartners: string[];
  missingRequestRecorded?: boolean;
  responseTimeMs: number;
  status: 'success' | 'fallback' | 'missing_item';
}

export interface MissingRequestRecord {
  id: string;
  timestamp: string;
  query: string;
  missingItem: string;
  missingCategory?: string;
  requestedLocation?: string;
  frequency: number;
  resolved: boolean;
  notes?: string;
  category?: string;
  count?: number;
  status?: string;
  location?: string;
}

export type AdminRole =
  | 'SUPER_ADMIN'
  | 'ADMIN'
  | 'CONTENT_MANAGER'
  | 'BUSINESS_MANAGER'
  | 'ANALYST'
  | 'SUPPORT';

export type SecurityClearanceTier =
  | 'TIER_1_CORE'
  | 'TIER_2_OPERATIONAL'
  | 'TIER_3_SUPPORT';

export interface AdminUser {
  id: string;
  username: string;
  name: string;
  email: string;
  role: AdminRole;
  phone?: string;
  nationalIdOrNin?: string;
  department?: string;
  securityClearance?: SecurityClearanceTier;
  securityClearanceLevel?: number | string;
  verifiedPersonal?: boolean;
  verifiedBy?: string;
  verifiedAt?: string;
  twoFactorEnabled?: boolean;
  lastLogin: string;
  active: boolean;
  createdAt?: string;
}

export interface AuditLogEntry {
  id: string;
  timestamp: string;
  adminId: string;
  adminName?: string;
  adminUsername?: string;
  role?: AdminRole;
  action: string;
  targetRecord?: string;
  targetEntity?: string;
  targetId?: string;
  previousValue?: string;
  newValue?: string;
  details?: string;
  result?: 'SUCCESS' | 'FAILURE' | 'WARNING' | string;
  entity?: string;
  ipAddress?: string;
}

export interface CashPowerTransaction {
  id: string;
  meterNumber: string;
  meterOwner: string;
  amountDalasi: number;
  phone: string;
  tokenGenerated: string;
  unitsKWh: number;
  tariffGMDPerKWh: number;
  timestamp: string;
  status: 'COMPLETED' | 'PENDING' | 'FAILED';
  isRealGateway: boolean; // clearly distinguish REAL vs DEMO/TEST
}

export interface GovernmentPaymentTransaction {
  id: string;
  serviceType: string;
  tinOrReference: string;
  taxpayerName: string;
  amountDalasi: number;
  phone: string;
  receiptNumber: string;
  status: 'COMPLETED' | 'PENDING';
  isRealGateway: boolean;
  timestamp: string;
}

export interface AIJobListing {
  id: string;
  title: string;
  type: 'Prompt Engineering' | 'Data Annotation' | 'Local Content Writer' | 'AI Tutor' | 'Freelance Microtask';
  compensation: string; // e.g., "D5,000 - D15,000 / month"
  location: string;
  company: string;
  skillsNeeded: string[];
  description: string;
  deadline: string;
}

// ===========================================================================
// SOHLA PRIVATE CONTROL CENTER TYPES (BACKWARD-COMPATIBLE EXTENSION)
// ===========================================================================

export type ControlCenterTab =
  | 'dashboard'
  | 'businesses'
  | 'products'
  | 'services'
  | 'categories'
  | 'locations'
  | 'beauty_bookings'
  | 'healthcare_services'
  | 'delivery_orders'
  | 'advertisements'
  | 'news'
  | 'events'
  | 'entertainment'
  | 'team'
  | 'super_team'
  | 'users'
  | 'business_owners'
  | 'ai_knowledge'
  | 'payments'
  | 'media'
  | 'approvals'
  | 'analytics'
  | 'security_audit'
  | 'admin_password'
  | 'system_health'
  | 'settings';

export type ExtendedPermission =
  | 'MANAGE_BUSINESSES'
  | 'VERIFY_PARTNERS'
  | 'MANAGE_PRODUCTS'
  | 'MANAGE_ADS'
  | 'MANAGE_TEAM'
  | 'MANAGE_SECURITY'
  | 'VIEW_AUDIT_LOGS'
  | 'VIEW_ANALYTICS'
  | 'EXPORT_DATA'
  | 'SYSTEM_CONFIG'
  | 'MANAGE_CONTENT'
  | 'MANAGE_BUSINESS_OWNERS'
  | 'MANAGE_AI_KNOWLEDGE'
  | 'MANAGE_PAYMENTS'
  | 'MANAGE_MEDIA'
  | 'MANAGE_SETTINGS'
  | 'APPROVE_CHANGES';

export type ContentStatus = 'draft' | 'pending_review' | 'approved' | 'published' | 'archived';

export interface NewsArticle {
  id: string;
  title: string;
  slug?: string;
  summary: string;
  content: string;
  category: string;
  author: string;
  coverImage: string;
  status: ContentStatus;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
  views?: number;
  tags?: string[];
}

export interface PlatformEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  time: string;
  location: string;
  image: string;
  organizer: string;
  contact: string;
  status: ContentStatus;
  createdAt: string;
  rsvpCount?: number;
}

export interface EntertainmentItem {
  id: string;
  title: string;
  description: string;
  mediaUrl: string;
  category: string;
  type: 'video' | 'music' | 'podcast' | 'showcase';
  status: ContentStatus;
  creator?: string;
  createdAt: string;
  duration?: string;
}

export interface AIKnowledgeEntry {
  id: string;
  title: string;
  category: string;
  content: string;
  active: boolean;
  expiresAt?: string;
  createdAt: string;
  updatedAt: string;
  author: string;
  priority?: number;
}

export interface BusinessOwner {
  id: string;
  partnerId: string;
  partnerName: string;
  ownerName: string;
  phone: string;
  email: string;
  nationalIdOrNin?: string;
  status: 'active' | 'pending_verification' | 'suspended';
  claimedAt: string;
  verifiedAt?: string;
  canEditProfile: boolean;
  canManageCatalog: boolean;
  canManageMedia: boolean;
  lastLogin?: string;
}

export interface ApprovalItem {
  id: string;
  entityType: 'business' | 'product' | 'service' | 'news' | 'event' | 'ad' | 'owner_claim';
  entityId: string;
  entityName: string;
  submittedBy: string;
  submittedRole: string;
  submissionDate: string;
  status: 'pending' | 'approved' | 'rejected';
  rejectionReason?: string;
  payload: any;
  reviewedBy?: string;
  reviewedAt?: string;
}

export interface PaymentSettings {
  cashPowerEnabled: boolean;
  governmentPaymentsEnabled: boolean;
  waveEnabled: boolean;
  qmoneyEnabled: boolean;
  afrimoneyEnabled: boolean;
  platformCommissionPercent: number;
  cashPowerFeeGMD: number;
  merchantCurrency: string;
  supportContact: string;
  payoutSchedule: 'DAILY_AUTOMATIC' | 'WEEKLY' | 'MONTHLY';
  testMode: boolean;
}

export interface PlatformSettings {
  platformName: string;
  country: string;
  currency: string;
  maintenanceMode: boolean;
  requireApprovalForEdits: boolean;
  aiModel: string;
  defaultDeliveryRadiusKm: number;
  businessClaimingEnabled: boolean;
  contactHotline: string;
  supportEmail: string;
  tagline?: string;
  supportPhone?: string;
  allowMerchantSelfRegistration?: boolean;
  aiModelGrounded?: boolean;
}

// ===========================================================================
// BEAUTY & WELLNESS BOOKING AND DELIVERY TYPES
// ===========================================================================

export type BeautyBookingStatus =
  | 'PENDING'
  | 'ACCEPTED'
  | 'CONFIRMED'
  | 'COMPLETED'
  | 'CANCELLED'
  | 'REJECTED';

export type DeliveryStatus =
  | 'PENDING'
  | 'ACCEPTED'
  | 'PICKUP_ASSIGNED'
  | 'PICKED_UP'
  | 'IN_TRANSIT'
  | 'DELIVERED'
  | 'CANCELLED'
  | 'REJECTED';

export type DeliveryType =
  | 'Food Delivery'
  | 'Express Courier'
  | 'Market Errands'
  | 'Package Delivery'
  | 'Documents'
  | 'Fragile Packages'
  | 'Same-Day Delivery'
  | 'Market Errand'
  | 'Document Dispatch'
  | 'Fragile Parcel';

export type BookingStatus = BeautyBookingStatus;

export type PaymentMethod = 'CASH' | 'WAVE' | 'QMONEY' | 'AFRIMONEY';

export type PaymentStatus = 'UNPAID' | 'PENDING_VERIFICATION' | 'PAID' | 'REFUNDED';

export interface BeautyBooking {
  id: string; // e.g. "bkg-17290001"
  bookingCode: string; // e.g. "BKG-GMB-8421"
  partnerId: string;
  partnerName: string;
  partnerLocation?: string;
  partnerPhone?: string;
  partnerWhatsapp?: string;
  serviceId?: string;
  serviceName: string;
  servicePrice: number; // in Dalasi (D)
  pricingType?: string;
  durationMinutes?: number;
  customerName: string;
  customerPhone: string;
  customerEmail?: string;
  customerNotes?: string;
  serviceLocationAddress?: string; // For home nursing & care visits
  serviceCategory?: string;
  serviceSubcategory?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  bookingDate: string; // YYYY-MM-DD
  bookingTime: string; // e.g. "10:30 AM"
  status: BeautyBookingStatus;
  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  rejectionReason?: string;
  cancellationReason?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DeliveryStatusHistoryItem {
  status: DeliveryStatus;
  timestamp: string;
  note?: string;
}

export interface DeliveryRequest {
  id: string; // e.g. "del-17290001"
  trackingCode: string; // e.g. "SHL-DEL-4912"
  deliveryType: DeliveryType;
  pickupLocation: string; // e.g. "Brusubi"
  pickupAddress: string;
  pickupContactName: string;
  pickupContactPhone: string;
  destinationLocation: string; // e.g. "Kololi"
  destinationAddress: string;
  dropoffLocation?: string;
  dropoffAddress?: string;
  recipientName: string;
  recipientPhone: string;
  packageDescription: string;
  packageWeightApprox?: string;
  fragile?: boolean;
  notes?: string;
  assignedPartnerId?: string;
  assignedPartnerName?: string;
  assignedPartnerPhone?: string;
  assignedPartnerWhatsapp?: string;
  courierPartnerName?: string;
  estimatedFee: number; // in Dalasi (D)
  deliveryFee?: number;
  status: DeliveryStatus;
  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  driverNotes?: string;
  cancellationReason?: string;
  rejectionReason?: string;
  statusHistory: DeliveryStatusHistoryItem[];
  createdAt: string;
  updatedAt: string;
}
